name: Deploy Django to EC2

on:
  push:
    branches:
      - develop  # Trigger when code is pushed to the develop branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.61.153.42 << 'EOF'
            cd ~/shzb/django-on-ec2
            git pull origin develop  # Make sure to pull the latest changes from develop branch
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate
            fuser -k 8000/tcp || true  # Kill any process using port 8000
            nohup python3 manage.py runserver 0.0.0.0:8000 &  # Run in background
            disown  # Detach the process so that it doesn't stop when the session closes
          EOF
