name: Deploy Django App to EC2

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.61.153.42 << 'EOF'
          cd ~/shzb/django-on-ec2
          git pull origin develop
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          pkill -f runserver || true
          nohup python3 manage.py runserver 0.0.0.0:8000 > output.log 2>&1 &
        EOF
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
